### ISSUE TITLE
Can't Access Login Page

### ISSUE THREAD

**Issue by benb17** [Abbondanzo/Modern-MyNEU#12]
Ever since I've installed the extension I can't reach the myneu homepage to login. I just receive the "Error: Session Expired" message, without any ability to reach the actual website. I've tried clearing cookies and the cache, but nothing. Even after uninstalling the extension I receive the same message. Myneu works on other browsers fine though. Any suggestions as to how to fix this?

**Comment by Abbondanzo** [comment]
We've discovered this issue this morning and are unable to find a link between the extension itself and MyNEU's session expired error. We are conducting tests at this moment to see what caused the error so that we can help/fix in any way possible.

**Comment by DarkAce65** [comment]
We're still unsure as to why this issue is occurring. It is possible that MyNEU is being updated at the moment.

I was able to fix it by completing the following steps:
1. Close all myneu.neu.edu tabs and windows.
2. Open Google Chrome's settings and click on **Show advanced settings...** at the bottom of the page
3. Click on the **Content settings...** button under the Privacy header
4. Click on the **All cookies and site data...** button under the Cookies header
5. Type "neu" into the **Search cookies** input box
6. Press the **Remove all** button
7. Navigate to this link [https://myneu.neu.edu/cp/home/loginf](https://myneu.neu.edu/cp/home/loginf)

**Comment by Abbondanzo** [comment]
After a few hours of experimentation, we have determined that this issue is a result of MyNEU updating and preparing its platform for a new portal coming late in the semester. [Their planned outage is scheduled for tomorrow but they are making some modifications today. Click here to view their message.](https://northeastern.statuspage.io/incidents/h8j4zx72wbnx) If you are still having this issue, contact the ITS Service Desk.
